spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.174:3306/sell?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  freemarker:
    request-context-attribute: request
  jackson:
      default-property-inclusion: non_null

server:
  context-path: /sell

wechat:
  mpAppId: wxd88093381fa5c198
  mpAppSecret: 25aa76a42d011e4e8a28b60e54f1cb06
  openAppId: #TODO微信开放平台AppId
  openAppSecret: #TODO微信开放平台密钥
  mchId: #TODO商户ID
  mchKey: #TODO商户密钥
  keyPath: #TODO商户证书路径
  notifyUrl: #TODO微信异步通知URL http://sell.com/sell/pay/notify
  templateId:
    orderStatus: #TODO微信消息模板ID

projectUrl:
  wechatMpAuthorize: http://q227z05133.iok.la #微信公众平台授权url
  wechatOpenAuthorize: http://q227z05133.iok.la #微信开发平台扫码登录授权url
  sell: http://q227z05133.iok.la #项目的url
